### PR TITLE
Reg active restore

### LINKED ISSUE #26: appAuthHelper loses reference to `reg.active`
```
setInterval(function () {
  // prevents the service worker thread from becoming idle and losing
  // the references we just passed into it.
  reg.active.postMessage({"message": "keepAlive"});
}, 1000);
```

Sporadically this seems to error every second saying that `reg.active` is undefined. Initially I thought it was down to my development environment occasionally getting confused with hot reloading but I've now witnessed it in a deployed environment too. 

I guess the quick fix would be to check that `postMessage` exists on `reg.active` but I'm not sure what is leading `reg.active` to sometimes be undefined in the first place. Any ideas?

### PR DESCRIPTION
**Pull request by jakefeasel**
Handles inactive service worker
    
    Checks to see if the originally-registered service worker is still active before using postMessage. If not, reactivates it.
    
    Fixes #26

### CODE REVIEW

**Comment by fetimo** [comment]
@jakefeasel thank you so much for this! I've tested it out with an intentionally failing service worker and have a few suggestions.

Namely that I check `savedReg && savedReg.active` as there's still the possibility that `savedReg` is undefined. 

I've also split out the return value in `registerServiceWorker` so that it returns the promise rather then the bound function. I've also assigned the setInterval to a variable so it can be cleared so there aren't multiple timers running on each try.

```javascript
registerIdentityProxy: function () {
  return new Promise((function (resolve, reject) {
      if (this.identityProxyPreference === "serviceWorker" && "serviceWorker" in navigator) {
          var savedReg;
          var registerServiceWorker = function() {
              var register = navigator.serviceWorker.register(this.appAuthConfig.serviceWorkerUri);
              register.then((function (reg) {
                  savedReg = reg;
                  navigator.serviceWorker.ready.then((function () {
                      // ...implementation
                  }).bind(this));
              }).bind(this));
              return register;
          }.bind(this);

          this.identityProxy = {
              // ...implementation
          };

          var tick = setInterval(function () {
              if (savedReg && savedReg.active) {
                  // prevents the service worker thread from becoming idle and losing
                  // the references we just passed into it.
                  savedReg.active.postMessage({"message": "keepAlive"});
              } else {
                  // In case the service worker still somehow manages to become inactive,
                  // re-registers it.
                  registerServiceWorker().catch((function (error) {
                      this.registerXHRProxy(); // not sure if this is needed?
                      clearInterval(tick);
                      reject(error);
                  }));
              }
          }, 1000);

          registerServiceWorker().catch((function () {
              this.registerXHRProxy();
              clearInterval(tick);
              resolve();
          }).bind(this));
      } else {
          this.registerXHRProxy();
          resolve();
      }
  }).bind(this));
}
```

Within the catch of the `registerServiceWorker` call in setInterval I don't know if it's a good idea to try to call `this.registerXHRProxy` again given that we know it already failed once?

**Comment by jakefeasel** [comment]
Thanks so much @fetimo ! I like your changes - especially the need to track and clear the timeout. I have taken your suggestions and refactored things a bit with the last commit. Please take another look when you have time and let me know what you think. Thanks again!

**Comment by fetimo** [comment]
@jakefeasel those changes look good to me, I'll pull it in and see if I get the error today and report back. Thanks Jake!

**Comment by fetimo** [comment]
Sorry, forgot to report back last week but didn't encounter the issue.

**Pull request merged**
